apiVersion: v1
kind: Pod
metadata:
  name: colocated-pod
spec:
  containers:
    - name: app
      image: nginx
    - name: helper
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Helper running'; sleep 5; done"]
