apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: ZGF0YWJhc2UuY29t # Base64 encoded values
  DB_USER: YWRtaW4= # Base64 encoded values
  DB_PASSWORD: cGFzc3dvcmQxMjM= # Base64 encoded values
